# OnChainAgents Wave Orchestration Configuration
# Multi-stage execution patterns inspired by SuperClaude

wave_orchestration:
  # Global Wave Settings
  global_config:
    auto_detection: true
    max_waves: 5
    min_complexity: 0.7
    min_files: 20
    min_operations: 2
    validation_required: true
    progressive_enhancement: true
    compound_intelligence: true
    
  # Activation Thresholds
  activation_thresholds:
    complexity_score: 0.7
    file_count: 20
    operation_types: 2
    domain_count: 3
    risk_level: 0.8
    
  # Wave Strategies
  strategies:
    progressive:
      name: "Progressive Enhancement"
      description: "Iterative improvement through incremental waves"
      stages:
        - name: discovery
          duration: 20%
          focus: analysis
          personas: [analyzer, chain_analyst]
          
        - name: planning
          duration: 15%
          focus: strategy
          personas: [architect, risk_manager]
          
        - name: implementation
          duration: 40%
          focus: execution
          personas: [defi_architect, developer]
          
        - name: validation
          duration: 15%
          focus: testing
          personas: [qa, security_auditor]
          
        - name: optimization
          duration: 10%
          focus: refinement
          personas: [performance, optimizer]
      
      resource_allocation:
        tokens_per_wave: 10000
        parallel_agents: 3
        retry_on_failure: true
        
    systematic:
      name: "Systematic Analysis"
      description: "Methodical examination through structured waves"
      stages:
        - name: assessment
          duration: 25%
          focus: current_state
          personas: [analyzer, auditor]
          
        - name: design
          duration: 20%
          focus: solution_design
          personas: [architect, defi_architect]
          
        - name: execution
          duration: 35%
          focus: implementation
          personas: [developer, chain_analyst]
          
        - name: verification
          duration: 20%
          focus: validation
          personas: [qa, security_auditor]
      
      resource_allocation:
        tokens_per_wave: 12000
        parallel_agents: 4
        retry_on_failure: false
        
    adaptive:
      name: "Adaptive Configuration"
      description: "Dynamic wave adjustment based on complexity"
      stages:
        - name: analysis
          duration: dynamic
          focus: complexity_assessment
          personas: [analyzer]
          
        - name: strategy
          duration: dynamic
          focus: approach_selection
          personas: [architect]
          
        - name: execution
          duration: dynamic
          focus: adaptive_implementation
          personas: dynamic
          
        - name: adjustment
          duration: dynamic
          focus: continuous_refinement
          personas: dynamic
      
      resource_allocation:
        tokens_per_wave: dynamic
        parallel_agents: dynamic
        retry_on_failure: true
        
    enterprise:
      name: "Enterprise Scale"
      description: "Large-scale orchestration for complex systems"
      stages:
        - name: discovery
          duration: 15%
          focus: comprehensive_analysis
          personas: [analyzer, architect, security_auditor]
          
        - name: architecture
          duration: 20%
          focus: system_design
          personas: [architect, defi_architect, risk_manager]
          
        - name: parallel_execution
          duration: 40%
          focus: distributed_implementation
          personas: [all_available]
          
        - name: integration
          duration: 15%
          focus: system_integration
          personas: [architect, qa]
          
        - name: deployment
          duration: 10%
          focus: production_readiness
          personas: [devops, security_auditor]
      
      resource_allocation:
        tokens_per_wave: 20000
        parallel_agents: 10
        retry_on_failure: true

# Wave Delegation Patterns
wave_delegation:
  delegation_strategies:
    files:
      description: "Delegate individual file analysis across waves"
      distribution: even
      coordination: sequential
      
    folders:
      description: "Delegate directory-level analysis across waves"
      distribution: hierarchical
      coordination: parallel
      
    tasks:
      description: "Delegate by task type across waves"
      distribution: priority_based
      coordination: dependency_aware
      
    domains:
      description: "Delegate by crypto domain across waves"
      distribution: expertise_based
      coordination: collaborative

# Wave Quality Gates
wave_quality_gates:
  enabled: true
  gates_per_wave:
    - wave: 1
      gates: [syntax, security_scan]
      
    - wave: 2
      gates: [type_check, logic_validation]
      
    - wave: 3
      gates: [implementation_quality, test_coverage]
      
    - wave: 4
      gates: [integration_test, performance]
      
    - wave: 5
      gates: [final_validation, deployment_ready]
  
  failure_handling:
    retry_wave: true
    max_retries: 2
    fallback_strategy: simplified
    escalation: manual_review

# Wave Performance Metrics
wave_metrics:
  tracking:
    - metric: completion_rate
      threshold: 90%
      
    - metric: quality_score
      threshold: 85%
      
    - metric: resource_efficiency
      threshold: 75%
      
    - metric: time_efficiency
      threshold: 80%
  
  optimization:
    learn_from_history: true
    adjust_strategies: true
    cache_patterns: true
    predict_complexity: true

# Wave Coordination Rules
coordination_rules:
  inter_wave_communication:
    enabled: true
    protocol: event_based
    data_sharing: selective
    
  parallel_wave_execution:
    max_parallel: 2
    resource_sharing: false
    conflict_resolution: priority_based
    
  wave_dependencies:
    strict_ordering: false
    dependency_checking: true
    failure_cascading: prevented
    
  checkpoint_management:
    auto_checkpoint: true
    checkpoint_frequency: per_wave
    rollback_capability: true
    state_preservation: comprehensive

# Wave Triggers
wave_triggers:
  automatic_triggers:
    - trigger: high_complexity
      condition: "complexity > 0.8"
      strategy: systematic
      
    - trigger: large_scale
      condition: "files > 100"
      strategy: enterprise
      
    - trigger: multi_domain
      condition: "domains > 3"
      strategy: adaptive
      
    - trigger: security_critical
      condition: "security_risk > 0.7"
      strategy: systematic
      
    - trigger: defi_optimization
      condition: "domain == 'defi' AND operation == 'optimize'"
      strategy: progressive
  
  manual_triggers:
    enabled: true
    override_auto: true
    require_confirmation: true

# Wave Resource Management
wave_resources:
  token_allocation:
    base_per_wave: 10000
    complexity_multiplier: 1.5
    max_per_wave: 30000
    total_budget: 100000
    
  memory_allocation:
    base_per_wave: 512
    scale_with_complexity: true
    max_per_wave: 2048
    
  time_allocation:
    base_per_wave: 60
    complexity_multiplier: 2.0
    max_per_wave: 300
    total_timeout: 1200
  
  agent_allocation:
    base_per_wave: 3
    scale_with_scope: true
    max_per_wave: 10
    reuse_across_waves: true

# Wave Recovery and Resilience
wave_resilience:
  failure_recovery:
    automatic_retry: true
    retry_delay: 5000
    max_retries: 3
    
  partial_failure_handling:
    continue_other_waves: true
    isolate_failures: true
    aggregate_partial_results: true
    
  emergency_protocols:
    circuit_breaker_integration: true
    degradation_aware: true
    resource_conservation: true
    
  rollback_strategy:
    checkpoint_based: true
    selective_rollback: true
    state_preservation: true
    audit_trail: comprehensive